# Практическое задание к уроку Алгоритм линейной регрессии. Градиентный спуск

In [46]:
import numpy as np
import matplotlib.pyplot as plt

In [47]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])


In [48]:
def calc_mse(y, y_pred):
  err = np.mean((y - y_pred)**2)
  return err

1. Подберите скорость обучения (alpha) и количество итераций:

In [179]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [180]:
for i in range(int(10/alpha)):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
  if i % 100 == 0:
    print(i, W, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001853
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434


*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [195]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [197]:
for i in range(int(10/alpha)):
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  W -= (alpha * (1/n * 2 * (np.dot(X , (y_pred - y)))))
  if i % 100 == 0:
    print(i, W, err)

0 [47.23088237  3.91094704] 45.937500872219864
100 [47.23169965  3.91079613] 45.93750010783411
200 [47.23198702  3.91074306] 45.93750001333172
300 [47.23208806  3.9107244 ] 45.93750000164824
400 [47.23212359  3.91071784] 45.937500000203784
500 [47.23213608  3.91071554] 45.937500000025196
600 [47.23214048  3.91071473] 45.93750000000313
700 [47.23214202  3.91071444] 45.93750000000038
800 [47.23214256  3.91071434] 45.93750000000003
900 [47.23214275  3.9107143 ] 45.937500000000014


*3: вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию 
начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn).

In [198]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
tol=46
W, alpha

(array([1. , 0.5]), 0.01)

In [199]:
while True:
  y_pred = np.dot(W, X)
  err = calc_mse(y, y_pred)
  W -= (alpha * (1/n * 2 * (np.dot(X , (y_pred - y)))))
  if err<tol:
    print(W, err)
    break

[46.89752492  3.97250405] 45.99896820983028
